import "%modules%/header/header";
import "%modules%/main-slider/main-slider";
import "%modules%/project-sliders/project-sliders";
import "%modules%/how-we-work/how-we-work";
import "%modules%/accordion/accordion";
import "%modules%/tabs/tabs";
import "%modules%/popups/popups";
import "%modules%/main-form/main-form";
import "%modules%/footer/footer";